// platform.proto — the one interface schema of the system (E-10).
//
// Rules that CI enforces:
//   1. Additive fields only. Field numbers die, they are never reassigned (SP-E10-3).
//   2. From the adapter through to the gate exactly one schema — the harness socket in the pod speaks
//      this one too.
//   3. The wire is Protobuf, the state stays relational: no blobs here, columns in Postgres.
//   4. No secret in a message, only references to one (SP-K01-5).
//
// Status: the contract from work package AP-2.1. Changes only through a decision in decisions/.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: platform.proto

package workpodv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlPlane_Enroll_FullMethodName          = "/workpod.v1.ControlPlane/Enroll"
	ControlPlane_RequestCapacity_FullMethodName = "/workpod.v1.ControlPlane/RequestCapacity"
	ControlPlane_SendHeartbeat_FullMethodName   = "/workpod.v1.ControlPlane/SendHeartbeat"
	ControlPlane_SubmitReport_FullMethodName    = "/workpod.v1.ControlPlane/SubmitReport"
	ControlPlane_SubmitEnvelope_FullMethodName  = "/workpod.v1.ControlPlane/SubmitEnvelope"
	ControlPlane_PublishEvent_FullMethodName    = "/workpod.v1.ControlPlane/PublishEvent"
)

// ControlPlaneClient is the client API for ControlPlane service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControlPlaneClient interface {
	// B-01: a single-use token for a node certificate with role and cell in the name
	Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error)
	// V-02: pull. The worker requests, the control plane never calls.
	RequestCapacity(ctx context.Context, in *CapacityRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Lease], error)
	SendHeartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Heartbeat, HaltNotice], error)
	SubmitReport(ctx context.Context, in *Report, opts ...grpc.CallOption) (*ReportAck, error)
	// T-01/T-02
	SubmitEnvelope(ctx context.Context, in *Envelope, opts ...grpc.CallOption) (*EnvelopeAck, error)
	PublishEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*EventAck, error)
}

type controlPlaneClient struct {
	cc grpc.ClientConnInterface
}

func NewControlPlaneClient(cc grpc.ClientConnInterface) ControlPlaneClient {
	return &controlPlaneClient{cc}
}

func (c *controlPlaneClient) Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollResponse)
	err := c.cc.Invoke(ctx, ControlPlane_Enroll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) RequestCapacity(ctx context.Context, in *CapacityRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Lease], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlPlane_ServiceDesc.Streams[0], ControlPlane_RequestCapacity_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CapacityRequest, Lease]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_RequestCapacityClient = grpc.ServerStreamingClient[Lease]

func (c *controlPlaneClient) SendHeartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Heartbeat, HaltNotice], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlPlane_ServiceDesc.Streams[1], ControlPlane_SendHeartbeat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Heartbeat, HaltNotice]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_SendHeartbeatClient = grpc.BidiStreamingClient[Heartbeat, HaltNotice]

func (c *controlPlaneClient) SubmitReport(ctx context.Context, in *Report, opts ...grpc.CallOption) (*ReportAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportAck)
	err := c.cc.Invoke(ctx, ControlPlane_SubmitReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) SubmitEnvelope(ctx context.Context, in *Envelope, opts ...grpc.CallOption) (*EnvelopeAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnvelopeAck)
	err := c.cc.Invoke(ctx, ControlPlane_SubmitEnvelope_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) PublishEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*EventAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventAck)
	err := c.cc.Invoke(ctx, ControlPlane_PublishEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlPlaneServer is the server API for ControlPlane service.
// All implementations must embed UnimplementedControlPlaneServer
// for forward compatibility.
type ControlPlaneServer interface {
	// B-01: a single-use token for a node certificate with role and cell in the name
	Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error)
	// V-02: pull. The worker requests, the control plane never calls.
	RequestCapacity(*CapacityRequest, grpc.ServerStreamingServer[Lease]) error
	SendHeartbeat(grpc.BidiStreamingServer[Heartbeat, HaltNotice]) error
	SubmitReport(context.Context, *Report) (*ReportAck, error)
	// T-01/T-02
	SubmitEnvelope(context.Context, *Envelope) (*EnvelopeAck, error)
	PublishEvent(context.Context, *Event) (*EventAck, error)
	mustEmbedUnimplementedControlPlaneServer()
}

// UnimplementedControlPlaneServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlPlaneServer struct{}

func (UnimplementedControlPlaneServer) Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Enroll not implemented")
}
func (UnimplementedControlPlaneServer) RequestCapacity(*CapacityRequest, grpc.ServerStreamingServer[Lease]) error {
	return status.Errorf(codes.Unimplemented, "method RequestCapacity not implemented")
}
func (UnimplementedControlPlaneServer) SendHeartbeat(grpc.BidiStreamingServer[Heartbeat, HaltNotice]) error {
	return status.Errorf(codes.Unimplemented, "method SendHeartbeat not implemented")
}
func (UnimplementedControlPlaneServer) SubmitReport(context.Context, *Report) (*ReportAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitReport not implemented")
}
func (UnimplementedControlPlaneServer) SubmitEnvelope(context.Context, *Envelope) (*EnvelopeAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitEnvelope not implemented")
}
func (UnimplementedControlPlaneServer) PublishEvent(context.Context, *Event) (*EventAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishEvent not implemented")
}
func (UnimplementedControlPlaneServer) mustEmbedUnimplementedControlPlaneServer() {}
func (UnimplementedControlPlaneServer) testEmbeddedByValue()                      {}

// UnsafeControlPlaneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlPlaneServer will
// result in compilation errors.
type UnsafeControlPlaneServer interface {
	mustEmbedUnimplementedControlPlaneServer()
}

func RegisterControlPlaneServer(s grpc.ServiceRegistrar, srv ControlPlaneServer) {
	// If the following call pancis, it indicates UnimplementedControlPlaneServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlPlane_ServiceDesc, srv)
}

func _ControlPlane_Enroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).Enroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_Enroll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).Enroll(ctx, req.(*EnrollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_RequestCapacity_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CapacityRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlPlaneServer).RequestCapacity(m, &grpc.GenericServerStream[CapacityRequest, Lease]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_RequestCapacityServer = grpc.ServerStreamingServer[Lease]

func _ControlPlane_SendHeartbeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControlPlaneServer).SendHeartbeat(&grpc.GenericServerStream[Heartbeat, HaltNotice]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_SendHeartbeatServer = grpc.BidiStreamingServer[Heartbeat, HaltNotice]

func _ControlPlane_SubmitReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Report)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).SubmitReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_SubmitReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).SubmitReport(ctx, req.(*Report))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_SubmitEnvelope_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Envelope)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).SubmitEnvelope(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_SubmitEnvelope_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).SubmitEnvelope(ctx, req.(*Envelope))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_PublishEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).PublishEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_PublishEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).PublishEvent(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlPlane_ServiceDesc is the grpc.ServiceDesc for ControlPlane service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlPlane_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "workpod.v1.ControlPlane",
	HandlerType: (*ControlPlaneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enroll",
			Handler:    _ControlPlane_Enroll_Handler,
		},
		{
			MethodName: "SubmitReport",
			Handler:    _ControlPlane_SubmitReport_Handler,
		},
		{
			MethodName: "SubmitEnvelope",
			Handler:    _ControlPlane_SubmitEnvelope_Handler,
		},
		{
			MethodName: "PublishEvent",
			Handler:    _ControlPlane_PublishEvent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RequestCapacity",
			Handler:       _ControlPlane_RequestCapacity_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SendHeartbeat",
			Handler:       _ControlPlane_SendHeartbeat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "platform.proto",
}

const (
	GitGate_Push_FullMethodName = "/workpod.v1.GitGate/Push"
)

// GitGateClient is the client API for GitGate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GitGateClient interface {
	Push(ctx context.Context, in *OutboxEntry, opts ...grpc.CallOption) (*Receipt, error)
}

type gitGateClient struct {
	cc grpc.ClientConnInterface
}

func NewGitGateClient(cc grpc.ClientConnInterface) GitGateClient {
	return &gitGateClient{cc}
}

func (c *gitGateClient) Push(ctx context.Context, in *OutboxEntry, opts ...grpc.CallOption) (*Receipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Receipt)
	err := c.cc.Invoke(ctx, GitGate_Push_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GitGateServer is the server API for GitGate service.
// All implementations must embed UnimplementedGitGateServer
// for forward compatibility.
type GitGateServer interface {
	Push(context.Context, *OutboxEntry) (*Receipt, error)
	mustEmbedUnimplementedGitGateServer()
}

// UnimplementedGitGateServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGitGateServer struct{}

func (UnimplementedGitGateServer) Push(context.Context, *OutboxEntry) (*Receipt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Push not implemented")
}
func (UnimplementedGitGateServer) mustEmbedUnimplementedGitGateServer() {}
func (UnimplementedGitGateServer) testEmbeddedByValue()                 {}

// UnsafeGitGateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GitGateServer will
// result in compilation errors.
type UnsafeGitGateServer interface {
	mustEmbedUnimplementedGitGateServer()
}

func RegisterGitGateServer(s grpc.ServiceRegistrar, srv GitGateServer) {
	// If the following call pancis, it indicates UnimplementedGitGateServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GitGate_ServiceDesc, srv)
}

func _GitGate_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OutboxEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitGateServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitGate_Push_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitGateServer).Push(ctx, req.(*OutboxEntry))
	}
	return interceptor(ctx, in, info, handler)
}

// GitGate_ServiceDesc is the grpc.ServiceDesc for GitGate service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GitGate_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "workpod.v1.GitGate",
	HandlerType: (*GitGateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Push",
			Handler:    _GitGate_Push_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "platform.proto",
}

const (
	EgressGate_Forward_FullMethodName = "/workpod.v1.EgressGate/Forward"
)

// EgressGateClient is the client API for EgressGate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EgressGateClient interface {
	Forward(ctx context.Context, in *EgressRequest, opts ...grpc.CallOption) (*EgressResponse, error)
}

type egressGateClient struct {
	cc grpc.ClientConnInterface
}

func NewEgressGateClient(cc grpc.ClientConnInterface) EgressGateClient {
	return &egressGateClient{cc}
}

func (c *egressGateClient) Forward(ctx context.Context, in *EgressRequest, opts ...grpc.CallOption) (*EgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EgressResponse)
	err := c.cc.Invoke(ctx, EgressGate_Forward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EgressGateServer is the server API for EgressGate service.
// All implementations must embed UnimplementedEgressGateServer
// for forward compatibility.
type EgressGateServer interface {
	Forward(context.Context, *EgressRequest) (*EgressResponse, error)
	mustEmbedUnimplementedEgressGateServer()
}

// UnimplementedEgressGateServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEgressGateServer struct{}

func (UnimplementedEgressGateServer) Forward(context.Context, *EgressRequest) (*EgressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Forward not implemented")
}
func (UnimplementedEgressGateServer) mustEmbedUnimplementedEgressGateServer() {}
func (UnimplementedEgressGateServer) testEmbeddedByValue()                    {}

// UnsafeEgressGateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EgressGateServer will
// result in compilation errors.
type UnsafeEgressGateServer interface {
	mustEmbedUnimplementedEgressGateServer()
}

func RegisterEgressGateServer(s grpc.ServiceRegistrar, srv EgressGateServer) {
	// If the following call pancis, it indicates UnimplementedEgressGateServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EgressGate_ServiceDesc, srv)
}

func _EgressGate_Forward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgressGateServer).Forward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EgressGate_Forward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgressGateServer).Forward(ctx, req.(*EgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EgressGate_ServiceDesc is the grpc.ServiceDesc for EgressGate service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EgressGate_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "workpod.v1.EgressGate",
	HandlerType: (*EgressGateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Forward",
			Handler:    _EgressGate_Forward_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "platform.proto",
}

const (
	Harness_QueryFacts_FullMethodName    = "/workpod.v1.Harness/QueryFacts"
	Harness_EnqueueEffect_FullMethodName = "/workpod.v1.Harness/EnqueueEffect"
	Harness_ReportGap_FullMethodName     = "/workpod.v1.Harness/ReportGap"
)

// HarnessClient is the client API for Harness service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HarnessClient interface {
	QueryFacts(ctx context.Context, in *FactQuery, opts ...grpc.CallOption) (*FactResult, error)
	EnqueueEffect(ctx context.Context, in *OutboxEntry, opts ...grpc.CallOption) (*EffectAck, error)
	ReportGap(ctx context.Context, in *GapReport, opts ...grpc.CallOption) (*EffectAck, error)
}

type harnessClient struct {
	cc grpc.ClientConnInterface
}

func NewHarnessClient(cc grpc.ClientConnInterface) HarnessClient {
	return &harnessClient{cc}
}

func (c *harnessClient) QueryFacts(ctx context.Context, in *FactQuery, opts ...grpc.CallOption) (*FactResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FactResult)
	err := c.cc.Invoke(ctx, Harness_QueryFacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *harnessClient) EnqueueEffect(ctx context.Context, in *OutboxEntry, opts ...grpc.CallOption) (*EffectAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EffectAck)
	err := c.cc.Invoke(ctx, Harness_EnqueueEffect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *harnessClient) ReportGap(ctx context.Context, in *GapReport, opts ...grpc.CallOption) (*EffectAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EffectAck)
	err := c.cc.Invoke(ctx, Harness_ReportGap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HarnessServer is the server API for Harness service.
// All implementations must embed UnimplementedHarnessServer
// for forward compatibility.
type HarnessServer interface {
	QueryFacts(context.Context, *FactQuery) (*FactResult, error)
	EnqueueEffect(context.Context, *OutboxEntry) (*EffectAck, error)
	ReportGap(context.Context, *GapReport) (*EffectAck, error)
	mustEmbedUnimplementedHarnessServer()
}

// UnimplementedHarnessServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHarnessServer struct{}

func (UnimplementedHarnessServer) QueryFacts(context.Context, *FactQuery) (*FactResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryFacts not implemented")
}
func (UnimplementedHarnessServer) EnqueueEffect(context.Context, *OutboxEntry) (*EffectAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnqueueEffect not implemented")
}
func (UnimplementedHarnessServer) ReportGap(context.Context, *GapReport) (*EffectAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportGap not implemented")
}
func (UnimplementedHarnessServer) mustEmbedUnimplementedHarnessServer() {}
func (UnimplementedHarnessServer) testEmbeddedByValue()                 {}

// UnsafeHarnessServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HarnessServer will
// result in compilation errors.
type UnsafeHarnessServer interface {
	mustEmbedUnimplementedHarnessServer()
}

func RegisterHarnessServer(s grpc.ServiceRegistrar, srv HarnessServer) {
	// If the following call pancis, it indicates UnimplementedHarnessServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Harness_ServiceDesc, srv)
}

func _Harness_QueryFacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FactQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarnessServer).QueryFacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Harness_QueryFacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarnessServer).QueryFacts(ctx, req.(*FactQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _Harness_EnqueueEffect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OutboxEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarnessServer).EnqueueEffect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Harness_EnqueueEffect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarnessServer).EnqueueEffect(ctx, req.(*OutboxEntry))
	}
	return interceptor(ctx, in, info, handler)
}

func _Harness_ReportGap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GapReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarnessServer).ReportGap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Harness_ReportGap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarnessServer).ReportGap(ctx, req.(*GapReport))
	}
	return interceptor(ctx, in, info, handler)
}

// Harness_ServiceDesc is the grpc.ServiceDesc for Harness service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Harness_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "workpod.v1.Harness",
	HandlerType: (*HarnessServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryFacts",
			Handler:    _Harness_QueryFacts_Handler,
		},
		{
			MethodName: "EnqueueEffect",
			Handler:    _Harness_EnqueueEffect_Handler,
		},
		{
			MethodName: "ReportGap",
			Handler:    _Harness_ReportGap_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "platform.proto",
}
